/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Employee;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Anar
 */
public class BackEmployeeMain extends javax.swing.JFrame {

    /**
     * Creates new form BackEmployeeMain
     */
    String id;
    Database db;
    Employee emp;
    
    public BackEmployeeMain(Database db, String id) {
        initComponents();
        this.id = id;
        this.db = db;
        fillMyProfile();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        idlbl = new javax.swing.JLabel();
        namelbl = new javax.swing.JLabel();
        maillbl = new javax.swing.JLabel();
        sdatelbl = new javax.swing.JLabel();
        addresslbl = new javax.swing.JLabel();
        branchlbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        updateInfoButton = new javax.swing.JButton();
        addActivityButton = new javax.swing.JButton();
        searchActivityPanelButton = new javax.swing.JButton();
        DynamicPanel = new javax.swing.JPanel();
        updatePanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        fnameField = new javax.swing.JTextField();
        currentPasswordField = new javax.swing.JPasswordField();
        lnameField = new javax.swing.JTextField();
        statlbl = new javax.swing.JLabel();
        mailField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        passwordConfirmField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        updatePasswordButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        addActivityPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        addActivityIDField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        addActivityNameField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        start_datePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel12 = new javax.swing.JLabel();
        end_datePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        addActivityStatusLbl = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        searchResultCount = new javax.swing.JLabel();
        searchEmployeeFnameLbl = new javax.swing.JLabel();
        searchActivityUpdateButton = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        searchByCmb = new javax.swing.JComboBox();
        searchActivityBranchLbl = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        searchActivityIDLbl = new javax.swing.JLabel();
        searchActivityRemoveButton = new javax.swing.JButton();
        searchActivityNameField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        searchActivityStartDate = new org.jdesktop.swingx.JXDatePicker();
        searchActivityEndDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchActivityInfoArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Back Employee Main");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "MY PROFILE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        idlbl.setText("ID : ");

        namelbl.setText("Name : ");

        maillbl.setText("Mail Address : ");

        sdatelbl.setText("Starting Date : ");

        addresslbl.setText("Address : ");

        branchlbl.setText("Branch ID :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(addresslbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idlbl, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sdatelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(145, 145, 145)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(namelbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(branchlbl)
                        .addGap(113, 113, 113))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(maillbl)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idlbl)
                    .addComponent(namelbl)
                    .addComponent(branchlbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maillbl)
                    .addComponent(sdatelbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(addresslbl)
                .addGap(27, 27, 27))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "MENU", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        updateInfoButton.setText("UPDATE INFO");
        updateInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInfoButtonActionPerformed(evt);
            }
        });

        addActivityButton.setText("ADD ACTIVITY");
        addActivityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActivityButtonActionPerformed(evt);
            }
        });

        searchActivityPanelButton.setText("SEARCH ACTIVITY");
        searchActivityPanelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActivityPanelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchActivityPanelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateInfoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addActivityButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(updateInfoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addActivityButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchActivityPanelButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DynamicPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        DynamicPanel.setLayout(new java.awt.CardLayout());

        jLabel8.setText("Current Password");

        fnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameFieldActionPerformed(evt);
            }
        });

        statlbl.setText("Status");

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("New Password");

        jLabel2.setText("First Name : ");

        jLabel3.setText("Last Name : ");

        jLabel7.setText("Confirm");

        jLabel4.setText("Mail Address : ");

        updatePasswordButton.setText("Update Password");
        updatePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePasswordButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Address : ");

        javax.swing.GroupLayout updatePanelLayout = new javax.swing.GroupLayout(updatePanel);
        updatePanel.setLayout(updatePanelLayout);
        updatePanelLayout.setHorizontalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updatePanelLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(updatePasswordButton)
                            .addGroup(updatePanelLayout.createSequentialGroup()
                                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(updateButton)
                                        .addGroup(updatePanelLayout.createSequentialGroup()
                                            .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updatePanelLayout.createSequentialGroup()
                                                        .addComponent(jLabel2)
                                                        .addGap(47, 47, 47))
                                                    .addGroup(updatePanelLayout.createSequentialGroup()
                                                        .addComponent(jLabel3)
                                                        .addGap(48, 48, 48)))
                                                .addGroup(updatePanelLayout.createSequentialGroup()
                                                    .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel5))
                                                    .addGap(38, 38, 38)))
                                            .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(fnameField, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lnameField, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(mailField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))))
                                    .addGroup(updatePanelLayout.createSequentialGroup()
                                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel8))
                                        .addGap(47, 47, 47)
                                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(passwordField)
                                            .addComponent(passwordConfirmField)
                                            .addComponent(currentPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(25, 25, 25))))
                    .addGroup(updatePanelLayout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(statlbl)))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        updatePanelLayout.setVerticalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(fnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(mailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateButton)
                .addGap(31, 31, 31)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(currentPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordConfirmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(updatePasswordButton)
                .addGap(27, 27, 27)
                .addComponent(statlbl)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        DynamicPanel.add(updatePanel, "card2");

        jLabel9.setText("Activity ID : ");

        addActivityIDField.setEditable(false);

        jLabel10.setText("Activity Name : ");

        jLabel11.setText("Starting Date :");

        jLabel12.setText("Ending Date : ");

        jLabel13.setText("Branch ID :");

        jLabel14.setText("Information :");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Add Activity");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        addActivityStatusLbl.setText("Status");

        javax.swing.GroupLayout addActivityPanelLayout = new javax.swing.GroupLayout(addActivityPanel);
        addActivityPanel.setLayout(addActivityPanelLayout);
        addActivityPanelLayout.setHorizontalGroup(
            addActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addActivityPanelLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(addActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addActivityPanelLayout.createSequentialGroup()
                        .addGroup(addActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(48, 48, 48)
                        .addGroup(addActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addActivityNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(start_datePicker, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(end_datePicker, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addActivityIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addActivityPanelLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jButton1))
                    .addGroup(addActivityPanelLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(addActivityStatusLbl)))
                .addContainerGap(262, Short.MAX_VALUE))
        );
        addActivityPanelLayout.setVerticalGroup(
            addActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addActivityPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(addActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(addActivityIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(addActivityNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(start_datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(addActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(end_datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(addActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addActivityPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel13))
                    .addGroup(addActivityPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(addActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(addActivityStatusLbl)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        DynamicPanel.add(addActivityPanel, "card3");

        searchResultCount.setText("Number Of Result");

        searchEmployeeFnameLbl.setText("Name : ");

        searchActivityUpdateButton.setText("Update");
        searchActivityUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActivityUpdateButtonActionPerformed(evt);
            }
        });

        searchByCmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "By ID", "By Name" }));

        searchActivityBranchLbl.setText("Branch ID : ");

        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jList1);

        searchActivityIDLbl.setText("ID : ");

        searchActivityRemoveButton.setText("Remove");
        searchActivityRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActivityRemoveButtonActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jLabel15.setText("Start Date");

        jLabel16.setText("End Date");

        jLabel17.setText("Info");

        searchActivityInfoArea.setColumns(20);
        searchActivityInfoArea.setRows(5);
        jScrollPane2.setViewportView(searchActivityInfoArea);

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(searchResultCount)
                        .addContainerGap())
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(searchByCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(searchPanelLayout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(searchActivityIDLbl)
                                                .addGroup(searchPanelLayout.createSequentialGroup()
                                                    .addComponent(searchEmployeeFnameLbl)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(searchActivityNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                                                    .addComponent(searchActivityBranchLbl)
                                                    .addGap(171, 171, 171))
                                                .addGroup(searchPanelLayout.createSequentialGroup()
                                                    .addComponent(jLabel15)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(searchActivityStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGap(12, 12, 12)))
                                            .addGroup(searchPanelLayout.createSequentialGroup()
                                                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(searchPanelLayout.createSequentialGroup()
                                                        .addComponent(jLabel17)
                                                        .addGap(43, 43, 43)
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(searchPanelLayout.createSequentialGroup()
                                                        .addComponent(jLabel16)
                                                        .addGap(24, 24, 24)
                                                        .addComponent(searchActivityEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, searchPanelLayout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(searchActivityRemoveButton)
                                        .addGap(58, 58, 58)
                                        .addComponent(searchActivityUpdateButton)))
                                .addContainerGap(87, Short.MAX_VALUE))
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(searchButton)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchByCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(searchActivityIDLbl)
                        .addGap(18, 18, 18)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchEmployeeFnameLbl)
                            .addComponent(searchActivityNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(searchActivityStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(searchActivityEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(searchActivityBranchLbl)
                        .addGap(29, 29, 29)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(searchActivityUpdateButton)
                                    .addComponent(searchActivityRemoveButton)))))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(searchResultCount)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DynamicPanel.add(searchPanel, "card4");

        jMenu1.setText("MENU");

        jMenuItem3.setText("Branch Detail");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setText("Log Out");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Quit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        EmployeeLogin el = new EmployeeLogin();
        el.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void fnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        String query = "update employee set fname = '"+fnameField.getText()+"', lname = '"+
        lnameField.getText()+"', mail = '" + mailField.getText()+"', address = ' " +
        addressField.getText()+"' where id = " + emp.getId();
        //JOptionPane.showMessageDialog(null, query);

        if(db.updateQuery(query))
        {
            statlbl.setText("Updated Successfully");
            //JOptionPane.showMessageDialog(null, "Updated Successfully");
            fillMyProfile();
        }
        else
        {
            statlbl.setText("Not Updated");
            JOptionPane.showMessageDialog(null, "Error occured during the update!!");
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void updatePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePasswordButtonActionPerformed
        // TODO add your handling code here:

        String query = "select passw from employee where id = " + emp.getId();
        ResultSet rs = db.getResultOfQuery(query);
        if(passwordField.getText().trim().equals("") || passwordConfirmField.getText().trim().equals(""))
        {
            statlbl.setText("Please Fill Password Fields!!");
        }
        else
        {
            try {
                if(rs.next())
                {
                    if(rs.getString("passw").equals(currentPasswordField.getText()))
                    {
                        if(passwordField.getText().equals(passwordConfirmField.getText()))
                        {
                            query = "update employee set passw = '" + passwordField.getText()+
                            "' where id = "+emp.getId();
                            if(db.updateQuery(query))
                            {
                                statlbl.setText("Password Updated successfully!");
                            }
                            else
                            {
                                statlbl.setText("Not Updated!!");
                            }

                        }
                        else
                        {
                            statlbl.setText("Password you entered doesn't match!!");
                        }

                    }
                    else
                    {
                        statlbl.setText("Password entered is not correc!!!");
                    }

                }
            }
            catch(Exception ex)
            {
            }

        }

        clearPasswordField();
    }//GEN-LAST:event_updatePasswordButtonActionPerformed

    private void updateInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInfoButtonActionPerformed
        // TODO add your handling code here:
        DynamicPanel.removeAll();
        DynamicPanel.add(updatePanel);
        DynamicPanel.repaint();
        DynamicPanel.revalidate();
        DynamicPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "UPDATE INFO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        fillupdate();
    }//GEN-LAST:event_updateInfoButtonActionPerformed

    private void addActivityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActivityButtonActionPerformed
        // TODO add your handling code here:
        DynamicPanel.removeAll();
        DynamicPanel.add(addActivityPanel);
        DynamicPanel.repaint();
        DynamicPanel.revalidate();
        DynamicPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "ADD ACTIVITY", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        fillActivityId();
        fillAddBranch();
    }//GEN-LAST:event_addActivityButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(addActivityIDField.getText().trim().equals(""))
        {
            addActivityStatusLbl.setText("Enter ID!!");
        }
        else if(addActivityNameField.getText().trim().equals("") || jTextArea1.getText().trim().equals(""))
        {
            addActivityStatusLbl.setText("Please fill above information");
        }
        else if(jComboBox1.getSelectedItem().toString().equals(""))
        {
            addActivityStatusLbl.setText("Please select Branch");
        }
        else if(start_datePicker.getDate()==null || end_datePicker.getDate()==null)
        {
            addActivityStatusLbl.setText("Please select Date");
        }
        else
        {
            int id = Integer.parseInt(addActivityIDField.getText());
             int branch = Integer.parseInt(jComboBox1.getSelectedItem().toString());
            Date start_date = start_datePicker.getDate();
            Date end_date = end_datePicker.getDate();
            String activityName = addActivityNameField.getText();
            String info = jTextArea1.getText();
        
            if(db.insertActivity(id, branch, activityName, start_date, end_date, info))
            {
                addActivityStatusLbl.setText("Added Successfully!");
                clearAddActivityField();
                
            
            }
            else
        {
            
            addActivityStatusLbl.setText("Not updated");
        }
            
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchActivityPanelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActivityPanelButtonActionPerformed
        // TODO add your handling code here:
        DynamicPanel.removeAll();
        DynamicPanel.add(searchPanel);
        DynamicPanel.repaint();
        DynamicPanel.revalidate();
        DynamicPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "SEARCH ACTIVITY", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
    }//GEN-LAST:event_searchActivityPanelButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        fillSearchList();
        searchField.setText("");
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchActivityRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActivityRemoveButtonActionPerformed
        // TODO add your handling code here:
        if(!(jList1.getSelectedValue()==null))
        {
            Activity activity = (Activity)jList1.getSelectedValue();
            String query = "delete from activity where id = "+activity.getId();
            if(db.updateQuery(query))
            {
                searchResultCount.setText("Removed");
                fillSearchList();
                clearSearchField();
            }
            else
            {
                searchResultCount.setText("Not Removed");

            }

        }
        else
        {
            searchResultCount.setText("Please select Activity");
        }

    }//GEN-LAST:event_searchActivityRemoveButtonActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        
        Activity activity = (Activity)jList1.getSelectedValue();
        searchActivityIDLbl.setText("ID : "+activity.getId());
        searchActivityNameField.setText(activity.getName());
        searchActivityStartDate.setDate(activity.getStart_date());
        searchActivityEndDate.setDate(activity.getEnd_date());
        searchActivityInfoArea.setText(activity.getInfo());
        searchActivityBranchLbl.setText("Branch ID : "+activity.getBranch());
    }//GEN-LAST:event_jList1ValueChanged

    private void searchActivityUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActivityUpdateButtonActionPerformed
        // TODO add your handling code here:
         if(!(jList1.getSelectedValue()==null))
        {
            Activity activity = (Activity)jList1.getSelectedValue();
            activity.setName(searchActivityNameField.getText());
            activity.setStart_date(searchActivityStartDate.getDate());
            activity.setEnd_date(searchActivityEndDate.getDate());
            activity.setInfo(searchActivityInfoArea.getText());
            if(db.updateActivity(activity))
            {
                searchResultCount.setText("Updated");
                clearSearchField();
            }
            else
            {
                searchResultCount.setText("Not Updated");
            }
        }
        else
        {
            searchResultCount.setText("Please select Employee");
        }
    }//GEN-LAST:event_searchActivityUpdateButtonActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        BranchDetail bd = new BranchDetail(db);
        bd.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    public void fillMyProfile()
    {
        String query = "select id, fname, lname, mail, address, start_date, branch_id from employee where id = "+ id;
                   
            ResultSet rs = db.getResultOfQuery(query);
            try {
                if(rs.next())
                {
                    emp = new Employee(rs.getInt("id"), rs.getString("fname"), rs.getString("lname"),
                            rs.getString("mail"), rs.getString("address"), rs.getString("start_date"), rs.getInt("branch_id"));
                    
                    idlbl.setText("ID : "+emp.getId());
                    namelbl.setText("Name : "+emp.getFname()+" "+emp.getLname());
                    branchlbl.setText("Branch ID : "+emp.getBranch());
                    maillbl.setText("Mail Address : "+emp.getMail());
                    addresslbl.setText("Address : "+emp.getAddress());
                    sdatelbl.setText("Starting date : "+rs.getDate("start_date").toString());
  
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Couldn't get admin information!!");
                }
              
            } catch (SQLException ex) {
                Logger.getLogger(EmployeeLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    public void fillupdate()
    {
        fnameField.setText(emp.getFname());
        lnameField.setText(emp.getLname());
        mailField.setText(emp.getMail());
        addressField.setText(emp.getAddress());
        
    }
    
    public void fillActivityId()
    {
        String idquery = "select idcount from myseq where seqname = 'activity'";
        ResultSet rs = db.getResultOfQuery(idquery);
        try {

            if(rs.next())
            {
                addActivityIDField.setText(rs.getString(1));
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Error Getting ID");
            }
           
        } catch (SQLException ex) {
            Logger.getLogger(AdminMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void clearSearchField()
    {
        searchActivityIDLbl.setText("ID : ");
        searchActivityNameField.setText("");
        searchActivityStartDate.setDate(null);
        searchActivityEndDate.setDate(null);
        searchActivityBranchLbl.setText("Branch ID : ");
        searchActivityInfoArea.setText("");
    }
    public void fillAddBranch()
    {
         String branchquery = "select branch_id from branch";
         ResultSet rs;
        rs = db.getResultOfQuery(branchquery);
        
        jComboBox1.removeAllItems();
        try {
            while(rs.next())
            {
                jComboBox1.addItem(rs.getString("branch_id"));
                
                
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Exception occured during retrieving branch list");
            Logger.getLogger(AdminMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void fillSearchList()
    {
        String query="";
        
       
            
             if(searchByCmb.getSelectedItem().toString().equals("By ID"))
        {
            query = "select id, branch_id, activity_name, start_time, end_time, info from activity where id like '"+searchField.getText()+"%'";
        }
        else if(searchByCmb.getSelectedItem().toString().equals("By Name"))
        {
            query = "select id, branch_id, activity_name, start_time, end_time, info from activity where activity_name like '"+searchField.getText()+"%'";
        }

        //JOptionPane.showMessageDialog(null, query);
        
        ArrayList<Activity> list = new ArrayList<Activity>();
        ResultSet rs = db.getResultOfQuery(query);
        int count = 0;
        try {
            while(rs.next())
            {
                count++;
                Date start_date = rs.getTimestamp(4);
                Date end_date = rs.getTimestamp(5);
                Activity activity = new Activity(rs.getInt(1), rs.getInt(2), rs.getString(3), start_date, end_date,rs.getString(6));
                list.add(activity);

            }
            jList1.setListData(list.toArray());
            searchResultCount.setText("Number of result : "+count);
        }
        catch(Exception e)
        {
            
        }
    }
    
    public void clearPasswordField()
    {
        currentPasswordField.setText("");
        passwordField.setText("");
        passwordConfirmField.setText("");
    }
    
    public void clearAddActivityField()
    {
        fillActivityId();
        fillAddBranch();
        addActivityNameField.setText("");
        start_datePicker.setDate(null);
        end_datePicker.setDate(null);
        jTextArea1.setText("");
        
        
    }
    /**
     * @param args the command line arguments
     */
   /*
    public static void main(String args[]) {
    
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BackEmployeeMain().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JButton addActivityButton;
    private javax.swing.JTextField addActivityIDField;
    private javax.swing.JTextField addActivityNameField;
    private javax.swing.JPanel addActivityPanel;
    private javax.swing.JLabel addActivityStatusLbl;
    private javax.swing.JTextField addressField;
    private javax.swing.JLabel addresslbl;
    private javax.swing.JLabel branchlbl;
    private javax.swing.JPasswordField currentPasswordField;
    private org.jdesktop.swingx.JXDatePicker end_datePicker;
    private javax.swing.JTextField fnameField;
    private javax.swing.JLabel idlbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField lnameField;
    private javax.swing.JTextField mailField;
    private javax.swing.JLabel maillbl;
    private javax.swing.JLabel namelbl;
    private javax.swing.JPasswordField passwordConfirmField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel sdatelbl;
    private javax.swing.JLabel searchActivityBranchLbl;
    private org.jdesktop.swingx.JXDatePicker searchActivityEndDate;
    private javax.swing.JLabel searchActivityIDLbl;
    private javax.swing.JTextArea searchActivityInfoArea;
    private javax.swing.JTextField searchActivityNameField;
    private javax.swing.JButton searchActivityPanelButton;
    private javax.swing.JButton searchActivityRemoveButton;
    private org.jdesktop.swingx.JXDatePicker searchActivityStartDate;
    private javax.swing.JButton searchActivityUpdateButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox searchByCmb;
    private javax.swing.JLabel searchEmployeeFnameLbl;
    private javax.swing.JTextField searchField;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JLabel searchResultCount;
    private org.jdesktop.swingx.JXDatePicker start_datePicker;
    private javax.swing.JLabel statlbl;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton updateInfoButton;
    private javax.swing.JPanel updatePanel;
    private javax.swing.JButton updatePasswordButton;
    // End of variables declaration//GEN-END:variables
}
