/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Employee;
import Customer.Branch;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Anar
 */
public class BranchDetail extends javax.swing.JFrame {

    /**
     * Creates new form BranchDetail
     */
    Database db;
    public BranchDetail(Database db) {
        initComponents();
        this.db = db;
        fillBranches();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BRANCH DETAILS");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("Total Branch Number : ");

        jLabel2.setText("Number Of Workers :");

        jLabel3.setText("Number Of Rooms : ");

        jLabel4.setText("Number of Activities : ");

        jLabel5.setText("Branch ID : ");

        jLabel6.setText("Branch Name : ");

        jLabel7.setText("Branch Location : ");

        jLabel8.setText("Total Income of Branch : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)))
                    .addComponent(jLabel8))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        try {
            // TODO add your handling code here:
            String employee_number="";
            String room_number="";
            String activity_number="";
            
            Branch branch = (Branch)jList1.getSelectedValue();
            
            String query = "select count(*) from employee where branch_id = "+branch.getId();
            ResultSet rs = db.getResultOfQuery(query);
            if(rs.next())
            {
                employee_number = rs.getString(1);
                
            }
            
            query = "select count(*) from room where branch_id = "+branch.getId();
            rs = db.getResultOfQuery(query);
            if(rs.next())
            {
                room_number = rs.getString(1);
                
            }
            query = "select count(*) from activity where branch_id = "+branch.getId();
            rs = db.getResultOfQuery(query);
            if(rs.next())
            {
                activity_number = rs.getString(1);
                
            }
            query = "select sum(payment_amount) from payment where branch_id = "+branch.getId();
            rs = db.getResultOfQuery(query);
            String total_income="";
            if(rs.next())
            {
                if(rs.getString(1)==null)
                {
                    total_income = "0";
                }
                else
                {
                    total_income = rs.getString(1);
                }
                
                
            }
            jLabel2.setText("Number of Workers : "+employee_number);
            jLabel3.setText("Number of Rooms : "+room_number);
            jLabel4.setText("Number of Activities : "+activity_number);
            jLabel5.setText("Branch ID : "+branch.getId());
            jLabel6.setText("Branch Name : " + branch.getName());
            jLabel7.setText("Branch Location : "+ branch.getLocation());
            jLabel8.setText("Total Income of Branch : "+total_income);
            
        }
        catch(SQLException e)
        {
            
        }
        
        
    }//GEN-LAST:event_jList1ValueChanged
  
    public void fillBranches()
    {
        ArrayList<Branch> branches = db.getBranch();
        jList1.setListData(branches.toArray());
        jLabel1.setText("Total Branch Number : "+branches.size());
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
