/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Employee;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Anar
 */
public class FrontEmployeeReserveRoom extends javax.swing.JFrame {

    /**
     * Creates new form FrontEmployeeReserveRoom
     */
    
    private int branch_id;
    private int customer_id;
    private Database db;
    public FrontEmployeeReserveRoom(int customer_id, int branch_id, Database db) {
        initComponents();
        this.branch_id = branch_id;
        this.customer_id = customer_id;
        this.db = db;
        jLabel1.setText("Customer ID : "+customer_id);
        fillRoomList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        totalroomsLabel = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        requestRoomButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        roomnumberLabel = new javax.swing.JLabel();
        roomtypeLabel = new javax.swing.JLabel();
        dailypriceLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        maxguestsLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("RESERVE ROOM");

        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText("Customer ID :");

        jLabel2.setText("Select Room");

        jLabel14.setText("Departure Date : ");

        totalroomsLabel.setText("Total Rooms : ");

        requestRoomButton.setText("Reserve Room");
        requestRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestRoomButtonActionPerformed(evt);
            }
        });

        jLabel12.setText("Room Properties");

        roomnumberLabel.setText("Room Number : ");

        roomtypeLabel.setText("Room Type : ");

        dailypriceLabel.setText("Daily Price : ");

        jLabel9.setText("Arrival Date : ");

        maxguestsLabel.setText("Max Guests : ");

        statusLabel.setText("Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel12))
                            .addComponent(roomnumberLabel)
                            .addComponent(roomtypeLabel)
                            .addComponent(maxguestsLabel)
                            .addComponent(dailypriceLabel)
                            .addComponent(totalroomsLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jXDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(51, 51, 51)
                                    .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(requestRoomButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(statusLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(roomnumberLabel)
                        .addGap(27, 27, 27)
                        .addComponent(roomtypeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(maxguestsLabel)
                        .addGap(18, 18, 18)
                        .addComponent(totalroomsLabel)
                        .addGap(18, 18, 18)
                        .addComponent(dailypriceLabel)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jXDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(requestRoomButton))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(statusLabel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void requestRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestRoomButtonActionPerformed
        // TODO add your handling code here:
        Room room = (Room)jList1.getSelectedValue();
        Date arrive_date = jXDatePicker1.getDate();
        Date departure_date = jXDatePicker2.getDate();
        if(arrive_date==null || departure_date == null)
        {
            statusLabel.setText("Please pick dates");
        }
        else if(room==null)
        {
            statusLabel.setText("Select room");
        }
        else
        {
            if(db.reserveRoomFrontEmployee(customer_id, branch_id, room , arrive_date, departure_date))
            {
                JOptionPane.showMessageDialog(null, "Reservation is done!!");
                this.dispose();
            }
            else
            {
                statusLabel.setText("Reservation is not done!!");
            }
        }
    }//GEN-LAST:event_requestRoomButtonActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        Room room = (Room)jList1.getSelectedValue();
        if(room!=null)
        {
            roomnumberLabel.setText("Room Number : "+room.getRoom_number());
            roomtypeLabel.setText("Room Type : "+room.getRoom_name());
            maxguestsLabel.setText("Max Guests : "+room.getMax_guests());
            totalroomsLabel.setText("Total Rooms : "+room.getTotal_rooms());
            dailypriceLabel.setText("Daily Price : "+room.getPrice());
            
        }
    }//GEN-LAST:event_jList1ValueChanged

//    /**
//     * @param args the command line arguments
//     */
//    /*public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrontEmployeeReserveRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrontEmployeeReserveRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrontEmployeeReserveRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrontEmployeeReserveRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrontEmployeeReserveRoom().setVisible(true);
//            }
//        });
//    }
    
    public void fillRoomList()
    {
        try {
            ArrayList<Room> rooms = new ArrayList<Room>();
            String query ="select room.ROOM_NUMBER, room_type.MAX_GUESTS, room_type.NAME, room_type.PRICE, room_type.TOTAL_ROOMS from room_type, room where room.TYPE_ID = room_type.id "
                    + "and status = 'empty' and room.branch_id = "+branch_id;
            
            ResultSet rs = db.getResultOfQuery(query);
            while(rs.next())
            {
                Room room = new Room(rs.getInt(1), rs.getString(3), rs.getInt(2), rs.getInt(5), rs.getInt(4));
                room.setBranch_id(branch_id);
                rooms.add(room);
 
            }
            jList1.setListData(rooms.toArray());
            
            
        } catch (SQLException ex) {
            Logger.getLogger(FrontEmployeeReserveRoom.class.getName()).log(Level.SEVERE, null, ex);
        }
        
                
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dailypriceLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    private javax.swing.JLabel maxguestsLabel;
    private javax.swing.JButton requestRoomButton;
    private javax.swing.JLabel roomnumberLabel;
    private javax.swing.JLabel roomtypeLabel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel totalroomsLabel;
    // End of variables declaration//GEN-END:variables
}
