/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Employee;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Anar
 */
public class FrontEmployeeReserveActivity extends javax.swing.JFrame {

    /**
     * Creates new form FrontEmployeeReserveActivity
     */
    private int branch_id;
    private int customer_id;
    private Database db;
    
    public FrontEmployeeReserveActivity(Database db, int customer_id, int branch_id) {
        initComponents();
        this.branch_id = branch_id;
        this.db = db;
        this.customer_id = customer_id;
        jLabel1.setText("Customer ID : "+customer_id);
        fillActivityList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        roomnumberLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        roomtypeLabel = new javax.swing.JLabel();
        maxguestsLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        totalroomsLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        requestRoomButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("RESERVE ACTIVITY");

        jLabel12.setText("Activity Properties");

        roomnumberLabel.setText("Activity ID : ");

        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        roomtypeLabel.setText("Activity Name : ");

        maxguestsLabel.setText("Start Time : ");

        jLabel1.setText("Customer ID :");

        totalroomsLabel.setText("End Time : ");

        statusLabel.setText("Status");

        jLabel2.setText("Select Activity");

        requestRoomButton.setText("Reserve Activity");
        requestRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestRoomButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Info");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel12))
                            .addComponent(roomnumberLabel)
                            .addComponent(roomtypeLabel)
                            .addComponent(maxguestsLabel)
                            .addComponent(totalroomsLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(requestRoomButton)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(statusLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(roomnumberLabel)
                        .addGap(27, 27, 27)
                        .addComponent(roomtypeLabel)
                        .addGap(18, 18, 18)
                        .addComponent(maxguestsLabel)
                        .addGap(18, 18, 18)
                        .addComponent(totalroomsLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(requestRoomButton))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(statusLabel)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        Activity activity = (Activity)jList1.getSelectedValue();
        if(activity!=null)
        {
            roomnumberLabel.setText("Activity ID : "+activity.getId());
            roomtypeLabel.setText("Activity Name : "+activity.getName());
            maxguestsLabel.setText("Start Time : "+activity.getStart_date());
            totalroomsLabel.setText("End Time : "+activity.getEnd_date());
            jTextArea1.setText(activity.getInfo());
            
        }
    }//GEN-LAST:event_jList1ValueChanged

    private void requestRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestRoomButtonActionPerformed
        // TODO add your handling code here:
        Activity activity = (Activity)jList1.getSelectedValue();
        if(activity!=null)
        {
            if(db.reserveActivityFrontEmployee(customer_id, branch_id, activity.getId()))
            {
                JOptionPane.showMessageDialog(null, "Activity Reservation is done");
                this.dispose();
            }
            else
            {
                statusLabel.setText("Activity reservation is not done");
            }
            
        }
        else
        {
            statusLabel.setText("Select activity first");
        }
       
    }//GEN-LAST:event_requestRoomButtonActionPerformed

    
    public void fillActivityList()
    {
        try {
            ArrayList<Activity> activities = new ArrayList<Activity>();
            String query =" select id, activity_name, start_time, end_time, info from " +
"activity where BRANCH_ID = "+branch_id;
            
            ResultSet rs = db.getResultOfQuery(query);
            while(rs.next())
            {
                Activity activity = new Activity(rs.getInt(1), branch_id, rs.getString(2), rs.getDate(3), rs.getDate(4), rs.getString(5));
                activities.add(activity);
            }
            jList1.setListData(activities.toArray());
            
            
        } catch (SQLException ex) {
            Logger.getLogger(FrontEmployeeReserveRoom.class.getName()).log(Level.SEVERE, null, ex);
        }
        
                
        
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrontEmployeeReserveActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrontEmployeeReserveActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrontEmployeeReserveActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrontEmployeeReserveActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrontEmployeeReserveActivity().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel maxguestsLabel;
    private javax.swing.JButton requestRoomButton;
    private javax.swing.JLabel roomnumberLabel;
    private javax.swing.JLabel roomtypeLabel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel totalroomsLabel;
    // End of variables declaration//GEN-END:variables
}
